dry-rb/dry-core

lib/dry/core/extensions.rb, spec/dry/core/extensions_spec.rb
A simple mixin for registering and loading arbitrary extension blocks.
=> Add Dry::Core::Extensions

lib/dry/core/class_builder.rb, spec/dry/core/class_builder_spec.rb
It's another port from rom-support, but I haven't implemented `Options` here. I'm going to have a closer look at using dry-initializer in rom, as far as I can tell, this suits as a `ROM::Options` replacement quite well. I've made some benchmarks today, it's faster than than ROM::Options by 20% or so. Also dry-t may require [some tweaks](https://github.com/dry-rb/dry-types/issues/123) to make type-checking more flexible
=> Add Dry::Core::ClassBuilder

lib/dry/core/extensions.rb
I can further edit this if you prefer, but this version seems succinct.
=> Typo fix (grammar): Remove "Allows to" prefix.

Gemfile, dry-core.gemspec, lib/dry/core/class_attributes.rb, lib/dry/core/errors.rb, spec/dry/core/class_attributes_spec.rb
@solnic @flash-gordon 
Add `type` option for defining class attributes 
```ruby
class NewClass
extend Dry::Core::ClassAttributes
defines :one, type: Test::Types::String
one '1'
end
```
This is interesting because we can use to control for invalid value passed to class attributes like in dry-struct defining `constructor_type`
```ruby
defines :constructor_type, type: Dry::Types['strict.symbol'].enum(:foo, :bar)
```
=> Add type option to class attribute

lib/dry/core/constants.rb, spec/dry/core/constants_spec.rb
This adds `Undefined.default` that can be useful for compacting `Undefined`-affected branching:
```ruby
def apply(val = Undefined, &block)
arg = Undefined.default(val, &block)
Curry.(@value).(arg)
end
```
=> Add Undefined.default

lib/dry/core/memoizable.rb, spec/dry/core/memoizable_spec.rb
This copies across `Memoizable` from ROM. Having it in dry-core will make it easier to use across a variety of different places.
=> Add Memoizable from ROM

lib/dry/core/class_builder.rb, spec/dry/core/class_builder_spec.rb, spec/fixtures/project.rb
(I've had more time to investigate #25 this morning and I think I've come up with a solution that will work in all cases.)
Particularly, Rails const autoloading. 
In a Rails app where you have models defined under app/models, these constants are loaded as they are referenced... but only when explicitly mentioned or you const_get them (essentially the same action).
When dry-core uses const_defined?, it will _not_ attempt to autoload this constant, and therefore it will not be defined. This causes the ClassBuilder to build a new anonymous class, which is the incorrect behaviour.
The correct behaviour would be to at least _attempt_ to get the constant -- which triggers autoloading -- before checking if it is defined. If the constant is unable to be const_get'd, then we ignore that error and …
=> Allow const autoloading a chance to act

lib/dry/core/constants.rb, spec/dry/core/constants_spec.rb
This is occasionally useful to map non-undefined values with a block. It saves one if-statement.
Clearly it's the functor of the maybe monad.
=> Add Undefined.map

lib/dry/core/constants.rb, spec/dry/core/constants_spec.rb
It should work the same way it does for Integer#dup i.e. return self back without exceptions
=> Add Undefined.{dup,clone}

lib/dry/core/constants.rb
The example says we should include `Dry::Core::Constants` but the code does not do it
=> Fix Documentation for Dry::Core::Constants [ci skip]

lib/dry/core/constants.rb, spec/dry/core/constants_spec.rb
It returns first non-undefined value
=> Add Undefined.coalesce

Gemfile, Gemfile.devtools, lib/dry/core/class_builder.rb
`Dry::Core` and all other Dry-rb gems requires ruby version 2.4 and above, that makes all the current guards useless since there's no way you can run this gem with something less than ruby 2.4.
Note: For jruby 9.2.12.0 -> RUBY_VERSION = '2.5.7'.
=> Removing guards for ruby 2.4

lib/dry/core/class_attributes.rb, lib/dry/core/errors.rb, spec/dry/core/class_attributes_spec.rb
Added a `coerce` option to Class Attributes instead of introducing breaking changes for the `type` option (related: https://github.com/dry-rb/dry-core/pull/42)
=> Implement coerce option for Class Attributes

lib/dry/core/memoizable.rb, spec/dry/core/memoizable_spec.rb, spec/support/memoized.rb, spec/support/shared_examples/memoizable.rb
See #46.
Two calls to a memoized method with different block arguments will now be cached separately.
=> Add support for memoized methods with block arguments

lib/dry/core/memoizable.rb, spec/dry/core/memoizable_spec.rb, spec/support/shared_examples/memoizable.rb
See: https://github.com/dry-rb/dry-core/pull/46
Comment `lib/dry/core/memoizable.rb:20` and/or `lib/dry/core/memoizable.rb:62` for specs to fail.
Normally I would use [doubles](https://relishapp.com/rspec/rspec-mocks/v/3-10/docs/verifying-doubles/using-an-instance-double) to verify method invocations (as seen in #46) but wanted to keep the changes to a minimum. Let me know if you want me to add this to the test suite. I'm currently not verifying that `bar_with_kwargs` is actually cached, only that the arguments are correct.
=> Add support for keyword arguments in Ruby 2.7+

lib/dry/core/deprecations.rb, spec/dry/core/deprecations_spec.rb
A new `uplevel` can be given on `Dry::Core::Deprecations.warn` &&
`Dry::Core::Deprecations.announce` to print information of the given
caller frame. E.g.:
```
irb(main):001:0> require 'dry/core/deprecations'
=> true
irb(main):002:1* class A
irb(main):003:2*   def a
irb(main):004:2*     Dry::Core::Deprecations.warn('a is deprecated', uplevel: 1)
irb(main):005:1*   end
irb(main):006:1* end
=> :a
irb(main):007:0* A.new.a
/home/root/bin/console:7:in `<main>' [deprecated] a is deprecated
=> true
``
=> Allow printing frame info on warn

lib/dry/core/deprecations.rb, lib/dry/core/equalizer.rb, lib/dry/core/memoizable.rb, spec/dry/core/memoizable_spec.rb, spec/support/memoized.rb
This removed using of `Kernel.eval`. It's not necessary to "resort" to such a thing. There's local_variable_get but even this can be avoided by careful picking bind names.
This commit also fixes ruby 3 keyword warnings from improper use of ruby2_keywords when there're no keywords in the definition. I'll add more specs in the following commits to make sure it doesn't break for various declarations.
Finally, I made zero args a special case, this way we save quite a few allocations which is nice for perf.
=> Refactor memoziation

lib/dry/core/deprecations.rb, spec/dry/core/deprecations_spec.rb
This changes the default `uplevel` arg for `caller_locations` from 1 to 2, which means we skip (1) the Deprecations.warn method itself, and then (2) the line from whatever gem is warning about the deprecation.
This means we end up showing the line from the code calling _into_ the deprecated behavior, which is (in most cases) where any kind of code fix should be made by the user.
Before this change, I was seeing the following kinds of deprecation warnings printed when running Hanami's test suite:
```
/Users/tim/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/dry-configurable-00f8b8e64898/lib/dry/configurable/class_methods.rb:41:in `setting' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a …
```
=> Show more relevant caller info for deprecation warnings

lib/dry/core/memoizable.rb, spec/dry/core/memoizable_spec.rb, spec/support/memoized.rb, spec/support/shared_examples/memoizable.rb
0.7.0 doesn't work with the new `...` syntax which returns `*`, `**`, and `&` as bind names. This PR fixes it but doesn't use the block argument as cache key (it's deprecated anyway).
=> Fix memoization of pass-through signature

changelog.yml, docsite/source/equalizer.html.md, docsite/source/index.html.md
Dry-equalized was deprecated as its own independent gem and integrated into `dry-core`, so its documentation should be under `dry-core` too.
Copied from https://github.com/dry-rb/dry-equalizer/blob/803df5de6a6b7d5bde9ebe7be6ea60664cf129a1/docsite/source/index.html.md and changed the metadata to match the other files in the same folder. I also changed references to `Dry::Equalizer` to `Dry::Core::Equalizer`, and `require 'dry-equalizer'` to `require 'dry/core/equalizer'`
=> Import dry-equalizer documentation

lib/dry/core/memoizable.rb
Just a simple typo for `singleton` that I found reading the code.
=> Fixes typo in Memoizable

lib/dry/core/class_attributes.rb
Correction to include the constant reference needed to avoid receiving `uninitialized constant Dry::Core::ClassAttributes::IDENTITY`.  Fixes #75
=> Correct missing constant for IDENTITY. Fixes #75

docsite/source/cache.html.md, docsite/source/deprecations.html.md, docsite/source/equalizer.html.md, docsite/source/extensions.html.md, lib/dry/core.rb, lib/dry/core/equalizer.rb, spec/dry/core/basic_object_spec.rb, spec/dry/core/cache_spec.rb, spec/dry/core/class_attributes_spec.rb, spec/dry/core/class_builder_spec.rb, spec/dry/core/constants_spec.rb, spec/dry/core/deprecations_spec.rb, spec/dry/core/descendants_tracker_spec.rb, spec/dry/core/equalizer/included_spec.rb, spec/dry/core/equalizer/legacy_name_spec.rb, spec/dry/core/equalizer/methods/eql_predicate_spec.rb, spec/dry/core/equalizer/methods/equality_operator_spec.rb, spec/dry/core/equalizer/universal_spec.rb, spec/dry/core/extensions_spec.rb, spec/dry/core/inflector_spec.rb, spec/dry/core/memoizable_spec.rb
As raised by @bkuhlmann in [bkuhlmann/wholable](https://github.com/bkuhlmann/wholable#influences)’s README, the version of dry-equalizer as moved to dry-core:
> doesn’t appear to work properly or be well supported. Even the documentation is not fully linked on the main page.
This PR addresses the “doesn’t appear to work properly” issue. See details below.
Once this is merged and released I’ll also update the 1.0 version of the docs to ensure _Equalizer_ properly appears in the sidebar.
Once both of these are done, I would also hope that the entirety of @bkuhlmann’s statement above is no longer true and can be updated 😄
Provide a `Dry::Core.Equalizer` method that builds the module when called as `include Dry::Core::Equalizer()` as documented. Previously, this method did not exist at all, …
=> Fix Dry::Core::Equalizer() usage

dry-core.gemspec
This prevents warnings about the upcoming removal of logger from the set of default gems:
```
lib/dry/core/deprecations.rb:3: warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5
```
=> Add logger as a gemspec dependency
